name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare Release ZIP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create release ZIP
        run: |
          cd custom_components
          zip -r ../toniebox.zip toniebox/
          cd ..

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: toniebox.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
